# 坚持

## 集中

~~nihao~~

离离原上草  一岁一枯荣

1. 11
2. 22
3. 33
4. 44

- 11
- 22
- 33

```python
import math
ptint("hellow world")
``` 

In [2]:
import numpy as np

In [3]:
arr1 = np.array([6,2,-7,2,8])
arr1

array([ 6,  2, -7,  2,  8])

In [10]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

分别打印元素的维度形状数量类型

In [7]:
print(arr1.ndim)
print(arr2.ndim)

1
2


In [8]:
print(arr1.shape)
print(arr2.shape)

(5,)
(2, 3)


In [11]:
print(arr1.size)
print(arr2.size)

5
6


In [12]:
print(arr1.dtype)
print(arr2.dtype)

int32
int32


创建6个0的一维数组

In [14]:
arr_all_0 = np.zeros(6)
arr_all_0

array([0., 0., 0., 0., 0., 0.])

In [ ]:
创建6个1的一维数组

In [15]:
arr_all_1 = np.ones(6)
arr_all_1

array([1., 1., 1., 1., 1., 1.])

In [ ]:
创建一维数组是10-20的偶数

In [19]:
arr_even = np.arange(10,21,2)
arr_even

array([10, 12, 14, 16, 18, 20])

In [20]:
arr11 = np.array([1,3,2,4,9])
arr22 = np.ones(5)
arr33 = np.zeros(3)

In [21]:
arr4 = np.concatenate([arr11,arr22,arr33])
arr4

array([1., 3., 2., 4., 9., 1., 1., 1., 1., 1., 0., 0., 0.])

In [27]:
sorted_arr11 = np.sort(arr11)
sorted_arr11 

array([1, 2, 3, 4, 9])

In [26]:
arr11.sort()
arr11

array([1, 2, 3, 4, 9])

In [29]:
print(arr11[2])
print(arr11[-3])

3
3


In [32]:
arr11[1:4]

array([2, 3, 4])

In [33]:
arr11 * -5

array([ -5, -10, -15, -20, -45])

In [39]:
print(arr11.max())
print(arr11.min())
print(arr11.mean())
print(arr11.sum())

9
1
3.8
19


In [40]:
arr11[(arr11>3)|(arr11<1)]

array([4, 9])

In [38]:
arr11 +arr22

array([ 2.,  3.,  4.,  5., 10.])

In [2]:
import pandas as pd

In [2]:
s1 = pd.Series([-1.2,3.7,2.5,-8.2,6.3])
s1

0   -1.2
1    3.7
2    2.5
3   -8.2
4    6.3
dtype: float64

In [4]:
print(s1.values)
print(s1.index)

[-1.2  3.7  2.5 -8.2  6.3]
RangeIndex(start=0, stop=5, step=1)


In [11]:
s2 = pd.Series([1,2,3,4,5],index=[5,4,3,2,1])
s2

5    1
4    2
3    3
2    4
1    5
dtype: int64

In [10]:
s2.iloc[1]

2


In [15]:
s2.loc[5:3]

5    1
4    2
3    3
dtype: int64

In [3]:
s3 = pd.Series({"小李":82,"小陈":93,"小张":91,"小曾":78,"小邓":68})
s3

小李    82
小陈    93
小张    91
小曾    78
小邓    68
dtype: int64

In [20]:
s3.loc["小张"] = 95
s3

小李    82
小陈    93
小张    95
小曾    78
小邓    68
dtype: int64

In [24]:
s3[(s3>80) & (s3<90)]
s3

小李    82
小陈    93
小张    95
小曾    78
小邓    68
dtype: int64